# Generated by Django 4.2.9 on 2024-03-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_status', models.CharField(max_length=30)),
                ('alarm_device', models.CharField(max_length=30)),
                ('alarm_measure', models.CharField(max_length=50)),
                ('alarm_description', models.TextField()),
                ('alarm_min', models.CharField(max_length=30)),
                ('alarm_max', models.CharField(max_length=30)),
                ('alarm_activation', models.CharField(max_length=30)),
                ('alarm_emails', models.CharField(max_length=50)),
                ('alarm_trigger', models.CharField(default='No', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Channel_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('connection_type', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=15)),
                ('port_conf', models.CharField(max_length=15)),
                ('signals', models.CharField(max_length=15)),
                ('value1', models.CharField(max_length=15)),
                ('value2', models.CharField(max_length=15)),
                ('value3', models.CharField(max_length=15)),
                ('value4', models.CharField(max_length=15)),
                ('value5', models.CharField(max_length=15)),
                ('value6', models.CharField(max_length=15)),
                ('value7', models.CharField(max_length=15)),
                ('value8', models.CharField(max_length=15)),
                ('value9', models.CharField(max_length=15)),
                ('value10', models.CharField(max_length=15)),
                ('value11', models.CharField(max_length=15)),
                ('value12', models.CharField(max_length=15)),
                ('value13', models.CharField(max_length=15)),
                ('value14', models.CharField(max_length=15)),
                ('value15', models.CharField(max_length=15)),
                ('value16', models.CharField(max_length=15)),
                ('value17', models.CharField(max_length=15)),
                ('value18', models.CharField(max_length=15)),
                ('value19', models.CharField(max_length=15)),
                ('value20', models.CharField(max_length=15)),
                ('value21', models.CharField(max_length=15)),
                ('value22', models.CharField(max_length=15)),
                ('value23', models.CharField(max_length=15)),
                ('value24', models.CharField(max_length=15)),
                ('value25', models.CharField(max_length=15)),
                ('value26', models.CharField(max_length=15)),
                ('value27', models.CharField(max_length=15)),
                ('value28', models.CharField(max_length=15)),
                ('value29', models.CharField(max_length=15)),
                ('value30', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_discreption', models.CharField(max_length=100)),
                ('num_devices', models.CharField(max_length=10)),
                ('licence_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('connection_type', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=50)),
                ('port_conf', models.CharField(max_length=30)),
                ('signals', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_status', models.CharField(max_length=30)),
                ('report_device', models.CharField(max_length=30)),
                ('report_measure', models.CharField(max_length=30)),
                ('report_interval_hours', models.CharField(max_length=30)),
                ('report_interval_minutes', models.CharField(max_length=30)),
                ('report_description', models.TextField()),
                ('report_activation', models.CharField(max_length=30)),
                ('report_emails', models.CharField(max_length=30)),
                ('report_timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('L1', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Channel_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.PositiveSmallIntegerField()),
                ('value', models.CharField(max_length=15)),
                ('value_2', models.CharField(max_length=15)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.device')),
            ],
            options={
                'unique_together': {('device', 'channel_number')},
            },
        ),
    ]
