# Generated by Django 4.2.9 on 2024-03-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel_test',
            new_name='Channel',
        ),
    ]
