# Generated by Django 4.2.9 on 2024-03-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_channel_test_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
