# Generated by Django 4.2.9 on 2024-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_channel_2_channel_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_1',
            name='device_id',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel_2',
            name='device_id',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel_3',
            name='device_id',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
