# Generated by Django 4.2.9 on 2024-03-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_channel_1_device_id_channel_2_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_1',
            name='value1_name',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value1_num_of_registers',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value1_register_address',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
    ]
