# Generated by Django 4.2.9 on 2024-03-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_channel_1_value1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_1',
            name='value10_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value10_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value10_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value11_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value11_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value11_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value12_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value12_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value12_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value13_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value13_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value13_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value14_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value14_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value14_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value15_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value15_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value15_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value16_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value16_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value16_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value17_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value17_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value17_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value18_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value18_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value18_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value19_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value19_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value19_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value20_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value20_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value20_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value21_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value21_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value21_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value22_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value22_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value22_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value23_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value23_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value23_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value24_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value24_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value24_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value25_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value25_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value25_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value26_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value26_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value26_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value27_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value27_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value27_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value28_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value28_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value28_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value29_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value29_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value29_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value2_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value2_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value2_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value30_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value30_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value30_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value3_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value3_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value3_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value4_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value4_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value4_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value5_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value5_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value5_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value6_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value6_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value6_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value7_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value7_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value7_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value8_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value8_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value8_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value9_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value9_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='channel_1',
            name='value9_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value1',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value10',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value11',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value12',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value13',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value14',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value15',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value16',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value17',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value18',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value19',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value1_name',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value1_num_of_registers',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value1_register_address',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value2',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value20',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value21',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value22',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value23',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value24',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value25',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value26',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value27',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value28',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value29',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value3',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value30',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value4',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value5',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value6',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value7',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value8',
            field=models.CharField(default='No', max_length=15),
        ),
        migrations.AlterField(
            model_name='channel_1',
            name='value9',
            field=models.CharField(default='No', max_length=15),
        ),
    ]
