# Generated by Django 4.2.9 on 2024-03-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_channel_1_value10_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('register_address', models.CharField(max_length=15)),
                ('num_of_registers', models.CharField(max_length=15)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.device')),
            ],
        ),
    ]
