# Generated by Django 4.2.9 on 2024-03-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel_1',
        ),
        migrations.DeleteModel(
            name='Channel_2',
        ),
        migrations.DeleteModel(
            name='Channel_3',
        ),
    ]
