# Generated by Django 4.2.9 on 2024-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_delete_channel_1_delete_channel_2_delete_channel_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='baud_rate',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='byte_size',
            field=models.CharField(default='1', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='parity',
            field=models.CharField(default='1', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='stop_bits',
            field=models.CharField(default='1', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='timeout',
            field=models.CharField(default='1', max_length=5),
            preserve_default=False,
        ),
    ]
