# Generated by Django 4.2.9 on 2024-03-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_modbusdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdata',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.register'),
            preserve_default=False,
        ),
    ]
