# Generated by Django 4.2.9 on 2024-03-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_modbusdata_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_status',
            field=models.CharField(default='online', max_length=30),
            preserve_default=False,
        ),
    ]
