# Generated by Django 4.2.9 on 2024-03-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alarm_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='channel',
        ),
    ]
