# Generated by Django 4.2.9 on 2024-03-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alarm_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='channel',
            field=models.ForeignKey(default='18', on_delete=django.db.models.deletion.CASCADE, to='website.device'),
            preserve_default=False,
        ),
    ]
