# Generated by Django 4.2.9 on 2024-03-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_report_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_measure',
        ),
    ]
