# Generated by Django 4.2.9 on 2024-04-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_report_report_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='alarm_triggered_at',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
