# Generated by Django 4.2.9 on 2024-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_register_polling_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdata',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
