# Generated by Django 4.2.9 on 2024-05-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_modbusdata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_device',
            field=models.TextField(),
        ),
    ]
