# Generated by Django 4.2.9 on 2024-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_report_report_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='channel',
        ),
        migrations.AddField(
            model_name='report',
            name='channel',
            field=models.ManyToManyField(to='website.device'),
        ),
    ]
