# Generated by Django 4.2.9 on 2024-05-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_report_channel_report_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_measure',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
