# Generated by Django 4.2.9 on 2024-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_report_report_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dividing_parameter',
            field=models.IntegerField(default='100'),
            preserve_default=False,
        ),
    ]
