# Generated by Django 4.2.9 on 2024-05-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_register_dividing_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
            ],
        ),
    ]
