# Generated by Django 4.2.9 on 2024-05-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_masteremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trigger_name', models.CharField(max_length=30)),
                ('trigger_data', models.CharField(max_length=30)),
                ('trigger_function', models.CharField(max_length=30)),
                ('trigger_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.device')),
            ],
        ),
    ]
