# Generated by Django 4.2.9 on 2024-05-26 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alarmtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmtrigger',
            name='trigger_alarm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.alarm'),
            preserve_default=False,
        ),
    ]
