# Generated by Django 4.2.9 on 2024-05-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alarmtrigger_trigger_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmtrigger',
            name='trigger_function',
        ),
    ]
