# Generated by Django 4.2.9 on 2024-06-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
