# Generated by Django 4.2.9 on 2024-06-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_device_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram_Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_1_title', models.CharField(max_length=50)),
                ('chart_1_1', models.CharField(max_length=50)),
                ('chart_1_2', models.CharField(max_length=50)),
                ('chart_1_3', models.CharField(max_length=50)),
                ('chart_1_4', models.CharField(max_length=50)),
                ('chart_1_5', models.CharField(max_length=50)),
                ('chart_2_title', models.CharField(max_length=50)),
                ('chart_2_1', models.CharField(max_length=50)),
                ('chart_2_2', models.CharField(max_length=50)),
                ('chart_2_3', models.CharField(max_length=50)),
                ('chart_2_4', models.CharField(max_length=50)),
                ('chart_2_5', models.CharField(max_length=50)),
                ('chart_3_title', models.CharField(max_length=50)),
                ('chart_3_1', models.CharField(max_length=50)),
                ('chart_3_2', models.CharField(max_length=50)),
                ('chart_3_3', models.CharField(max_length=50)),
                ('chart_3_4', models.CharField(max_length=50)),
                ('chart_3_5', models.CharField(max_length=50)),
                ('chart_4_title', models.CharField(max_length=50)),
                ('chart_4_1', models.CharField(max_length=50)),
                ('chart_4_2', models.CharField(max_length=50)),
                ('chart_4_3', models.CharField(max_length=50)),
                ('chart_4_4', models.CharField(max_length=50)),
                ('chart_4_5', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.device')),
            ],
        ),
    ]
