# Generated by Django 4.2.9 on 2024-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_diagram_charts'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_1',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_2',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_3',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_4',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_5',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_1',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_2',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_3',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_4',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_5',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
