# Generated by Django 4.2.9 on 2024-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_diagram_charts_chart_5_1_diagram_charts_chart_5_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_1_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_1_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_1_thresh_hold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_2_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_2_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_2_thresh_hold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_3_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_3_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_3_thresh_hold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_4_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_4_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_4_thresh_hold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_5_thresh_hold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagram_charts',
            name='chart_6_thresh_hold',
            field=models.IntegerField(default=1),
        ),
    ]
