# Generated by Django 4.2.9 on 2024-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_diagram_charts_chart_1_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdata',
            name='polling_interval',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
