# Generated by Django 4.2.9 on 2024-07-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_modbusdata_polling_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram_charts',
            name='graph_1',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
