# Generated by Django 4.2.9 on 2024-07-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_diagram_charts_graph_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='parameter_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
