# Generated by Django 4.2.9 on 2024-08-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_register_parameter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_date_from',
            field=models.DateField(default='1999-12-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='report_date_to',
            field=models.DateField(default='1999-12-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='report_date_type',
            field=models.CharField(default='1999-12-9', max_length=50),
            preserve_default=False,
        ),
    ]
