# Generated by Django 4.2.9 on 2024-08-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_report_report_date_from_report_report_date_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='channel',
        ),
    ]
