# Generated by Django 4.2.9 on 2024-08-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_remove_report_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_date_from',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_date_to',
        ),
    ]
