# Generated by Django 4.2.9 on 2025-02-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_remove_report_report_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram_charts',
            name='graph_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
