# Generated by Django 4.2.9 on 2025-02-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_diagram_charts_graph_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrical_Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.TextField()),
                ('measures', models.TextField()),
            ],
        ),
    ]
